[package]
name = "anomaly"
version = "0.1.0"
authors = ["Calmynt <mctech26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
lazy_static = "1.4.0"
rand = "0.7.3"
